//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoBigTruck {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localize() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoBigTruck.Properties.Localize", typeof(Localize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add new rule.
        /// </summary>
        public static string AddNewRule {
            get {
                return ResourceManager.GetString("AddNewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check target building&apos;s size.
        /// </summary>
        public static string CheckTargetSize {
            get {
                return ResourceManager.GetString("CheckTargetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max building&apos;s length.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max building&apos;s width.
        /// </summary>
        public static string MaxWidth {
            get {
                return ResourceManager.GetString("MaxWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Big trucks dont deliver goods to stores.
        /// </summary>
        public static string Mod_Description {
            get {
                return ResourceManager.GetString("Mod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [NEW] Added missing dependencies checker.
        ///[TRANSLATION] Added Finnish, German, Japanese, Russian translations..
        /// </summary>
        public static string Mod_WhatsNewMessage1_1 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [FIXED] Fixed errors that caused the mod to not work.
        ///[FIXED] Fixed the missing &quot;Big Truck&quot; option in AVO mod.
        ///[TRANSLATION] Added Chinese, Dutch and Italian translations..
        /// </summary>
        public static string Mod_WhatsNewMessage1_2 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [TRANSLATION] Added Spanish translations..
        /// </summary>
        public static string Mod_WhatsNewMessage1_2_1 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [TRANSLATION] Added Korean translation..
        /// </summary>
        public static string Mod_WhatsNewMessage1_2_2 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [TRANSLATION] Added Hungarian translation..
        /// </summary>
        public static string Mod_WhatsNewMessage1_2_3 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [TRANSLATION] Added Danish, Portuguese and Turkish translations.
        /// </summary>
        public static string Mod_WhatsNewMessage1_2_4 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [UPDATED] Added Plazas &amp; Promenades DLC support..
        /// </summary>
        public static string Mod_WhatsNewMessage1_3 {
            get {
                return ResourceManager.GetString("Mod_WhatsNewMessage1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rules.
        /// </summary>
        public static string RulesTab {
            get {
                return ResourceManager.GetString("RulesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source building&apos;s type.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Industry.
        /// </summary>
        public static string SourceIndustry {
            get {
                return ResourceManager.GetString("SourceIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outside.
        /// </summary>
        public static string SourceOutside {
            get {
                return ResourceManager.GetString("SourceOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warehouse.
        /// </summary>
        public static string SourceWarehouse {
            get {
                return ResourceManager.GetString("SourceWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target building&apos;s type.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eco.
        /// </summary>
        public static string TargetEco {
            get {
                return ResourceManager.GetString("TargetEco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на High.
        /// </summary>
        public static string TargetHigh {
            get {
                return ResourceManager.GetString("TargetHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Leisure.
        /// </summary>
        public static string TargetLeisure {
            get {
                return ResourceManager.GetString("TargetLeisure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Low.
        /// </summary>
        public static string TargetLow {
            get {
                return ResourceManager.GetString("TargetLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tourist.
        /// </summary>
        public static string TargetTourist {
            get {
                return ResourceManager.GetString("TargetTourist", resourceCulture);
            }
        }
    }
}
